component_depth: 1
languages:
- java
exclude:
- ./bin/.*
- ./bin/META-INF/.*
- ./bin/META-INF/services/.*
- ./bin/org/.*
- ./bin/org/cyberneko/.*
- ./bin/org/cyberneko/html/.*
- ./bin/org/cyberneko/html/filters/.*
- ./bin/org/cyberneko/html/parsers/.*
- ./bin/org/cyberneko/html/res/.*
- ./bin/org/cyberneko/html/xercesbridge/.*
- ./bin/sample/.*
- ./data/.*
- ./data/a/.*
- ./data/canonical/.*
- ./data/document-fragment/.*
- ./data/forms/.*
- ./data/frameset/.*
- ./data/insert-namespace/.*
- ./data/meta/.*
- ./data/misc/.*
- ./data/normalize-attrs/.*
- ./data/noxxx/.*
- ./data/strip-delims/.*
- ./data/table/.*
- ./data/unknown/.*
- ./doc/.*
- ./doc/javadoc/.*
- ./doc/javadoc/org/.*
- ./doc/javadoc/org/cyberneko/.*
- ./doc/javadoc/org/cyberneko/html/.*
- ./doc/javadoc/org/cyberneko/html/class-use/.*
- ./doc/javadoc/org/cyberneko/html/filters/.*
- ./doc/javadoc/org/cyberneko/html/filters/class-use/.*
- ./doc/javadoc/org/cyberneko/html/parsers/.*
- ./doc/javadoc/org/cyberneko/html/parsers/class-use/.*
- ./lib/.*
- ./lib/xerces-2.0.2/.*
- ./lib/xerces-2.1.0/.*
- ./lib/xerces-2.2.1/.*
- ./lib/xerces-2.3.0/.*
- ./lib/xerces-2.8.1/.*
- ./lib/xerces-2.9.1/.*
- ./lib/xerces-minimal/.*
- ./test/.*
- ./test/java/.*
- ./test/java/org/.*
- ./test/java/org/cyberneko/.*
- ./test/java/org/cyberneko/html/.*
- ./test/java/org/cyberneko/html/filters/.*
